import { Inter } from 'next/font/google'
import '/app/comments/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hardware Recycler',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
